name: Document Code
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: main
      
      #- name: Swift Doc
      #  uses: SwiftDocOrg/swift-doc@1.0.0-rc.1
      #  with:
      #    inputs: "Sources"
      #    module-name: KukaiCryptoSwift
      #    format: "html"
      #    output: "Documentation"
      #    base-url: "https://kukai-crypto-swift.kukai.app/"

      - name: Documentation
        uses: sersoft-gmbh/swifty-docs-action@v3
        with:
          output: Documentation
          #hosting-base-path: "https://kukai-crypto-swift.kukai.app/"


      - name: Update Permissions
        run: 'sudo chown --recursive $USER Documentation'
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: Documentation